disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace

opt_in_rules: # rules that are only enabled when included in 
`.swiftlint.yml`
  - empty_count
  - file_header
  - empty_string
 

excluded: # paths to ignore during linting. Takes precedence over 
`included`.
  - Carthage
  - Pods
  - fastlane
  - fastlane/*
  - .build
  - .build/*
  - .swiftlint.yml
  - .git
  - .git/*

 
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"


